apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\jakub\AppData\Local\Microsoft\WinGet\Links\kompose.exe convert
    kompose.version: 1.30.0 (9d8dcb518)
  creationTimestamp: null
  labels:
    io.kompose.service: collector
  name: collector
  namespace: mutation-app
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: collector
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\jakub\AppData\Local\Microsoft\WinGet\Links\kompose.exe convert
        kompose.version: 1.30.0 (9d8dcb518)
      creationTimestamp: null
      labels:
        io.kompose.network/docker-oltp-bridge: "true"
        io.kompose.service: collector
    spec:
      containers:
        - args:
            - --config=/etc/config/collector.yaml
          image: otel/opentelemetry-collector-contrib:0.75.0
          name: collector
          ports:
            - containerPort: 4317
              hostPort: 4317
              protocol: TCP
          resources: {}
          volumeMounts:
            - mountPath: /etc/config
              name: collector-config
      restartPolicy: Always
      volumes:
        - name: collector-config
          configMap: 
            name: collector-config
            items:
              - key: collector.yaml
                path: collector.yaml
status: {}
