apiVersion: v1
kind: Service
metadata:
  annotations:
  creationTimestamp: null
  name: mutation-orchestrator
  namespace: mutation-app
spec:
  ports:
    - name: "5208"
      port: 5208
      targetPort: 5208
  selector:
    io.kompose.service: mutation-orchestrator
status:
  loadBalancer: {}
