apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\jakub\AppData\Local\Microsoft\WinGet\Links\kompose.exe convert
    kompose.version: 1.30.0 (9d8dcb518)
  creationTimestamp: null
  labels:
    io.kompose.service: prometheus
  name: prometheus
  namespace: mutation-app
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: prometheus
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\jakub\AppData\Local\Microsoft\WinGet\Links\kompose.exe convert
        kompose.version: 1.30.0 (9d8dcb518)
      creationTimestamp: null
      labels:
        io.kompose.network/docker-grafana-bridge: "true"
        io.kompose.network/docker-oltp-bridge: "true"
        io.kompose.service: prometheus
    spec:
      containers:
        - args:
            - --web.enable-remote-write-receiver
            - --config.file=/etc/prometheus/prometheus.yml
          image: prom/prometheus:v2.43.0
          name: prometheus
          resources: {}
          volumeMounts:
            - mountPath: /etc/prometheus
              name: prometheus-config
      restartPolicy: Always
      volumes:
        - name: prometheus-config
          configMap: 
            name: prometheus-config
            items:
              - key: prometheus.yml
                path: prometheus.yml
status: {}
