apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\jakub\AppData\Local\Microsoft\WinGet\Links\kompose.exe convert
    kompose.version: 1.30.0 (9d8dcb518)
  creationTimestamp: null
  labels:
    io.kompose.service: rabbitmq
  name: rabbitmq
  namespace: mutation-app
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: rabbitmq
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\jakub\AppData\Local\Microsoft\WinGet\Links\kompose.exe convert
        kompose.version: 1.30.0 (9d8dcb518)
      creationTimestamp: null
      labels:
        io.kompose.network/docker-main-bridge: "true"
        io.kompose.service: rabbitmq
    spec:
      containers:
        - env:
            - name: RABBITMQ_DEFAULT_PASS
              value: mypassword
            - name: RABBITMQ_DEFAULT_USER
              value: myuser
          image: rabbitmq:3.11.13-management-alpine
          name: rabbitmq
          volumeMounts:
            - mountPath: /etc/rabbitmq
              name: rabbitmq-config 
          ports:
            - containerPort: 5672
              hostPort: 5672
              protocol: TCP
            - containerPort: 15672
              hostPort: 15672
              protocol: TCP
          resources: {}
      restartPolicy: Always
      volumes:
        - name: rabbitmq-config
          configMap: 
            name: rabbitmq-config
            items:
              - key: rabbitmq.conf
                path: rabbitmq.conf
status: {}
