apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\jakub\AppData\Local\Microsoft\WinGet\Links\kompose.exe convert
    kompose.version: 1.30.0 (9d8dcb518)
  creationTimestamp: null
  labels:
    io.kompose.service: collector
  name: collector
  namespace: mutation-app
spec:
  ports:
    - name: "4317"
      port: 4317
      targetPort: 4317
  selector:
    io.kompose.service: collector
status:
  loadBalancer: {}
