version: "3.8"

networks:
  grafana-bridge:
  oltp-bridge:
  main-bridge:
  mongo-bridge:

services:
  rabbitmq:
    container_name: "rabbitmq"
    image: rabbitmq:3.11.13-management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=myuser
      - RABBITMQ_DEFAULT_PASS=mypassword
    ports:
      # AMQP protocol port
      - '5672:5672'
      # HTTP management UI
      - '15672:15672'
    networks:
     - main-bridge
        
  grafana:
    image: grafana/grafana:8.2.6
    container_name: "grafana"
    volumes:
      - ./data/grafana-data/datasources:/etc/grafana/provisioning/datasources
      - ./data/grafana-data/dashboards-provisioning:/etc/grafana/provisioning/dashboards
      - ./data/grafana-data/dashboards:/var/lib/grafana/dashboards
    ports:
      - "3000:3000"
    networks: 
      - grafana-bridge
  
  prometheus:
    image: prom/prometheus:v2.43.0
    container_name: "prometheus"
    volumes:
      - ./prometheus/:/etc/prometheus
    command: [ "--web.enable-remote-write-receiver", "--config.file=/etc/prometheus/prometheus.yml" ]
    networks: 
      - grafana-bridge
      - oltp-bridge
  
  loki:
    image: grafana/loki:2.8.0
    container_name: "loki"
    ports:
      - "3100:3100"
    command: [ "-config.file=/etc/loki/local-config.yaml" ]
    networks:
      - grafana-bridge
      - oltp-bridge
  
#  tempo:
#    image: grafana/tempo:main-9996433-amd64
#    container_name: "tempo"
#    command: [ "-config.file=/etc/tempo.yaml" ]
#    volumes:
#      - ./tempo/tempo.yaml:/etc/tempo.yaml
#    networks:
#      - grafana-bridge
#      - oltp-bridge
       
  collector:
    image: otel/opentelemetry-collector-contrib:0.75.0
    container_name: "collector"
    command: [ "--config=/etc/collector.yaml" ]
    volumes:
      - ./collector:/etc
    ports: 
      - "4317:4317"
    networks:
      - oltp-bridge

  mutation-app:
    image: mutation-app:latest
    container_name: "mutation-app"
    environment:
     - SUPERVISOR_ADDRESS=mutation-orchestrator
     - SUPERVISOR_PORT=5208
     - QUEUE_ADDRESS=rabbitmq
     - QUEUE_LOGIN=myuser
     - QUEUE_PASSWORD=mypassword
     - QUEUE_PORT=5672
     - OPTL_COLLECTOR=http://collector:4317
    networks:
     - main-bridge
     - oltp-bridge
    links:
      - mutation-orchestrator
      - rabbitmq
       
  mutation-app2:
    image: mutation-app:latest
    container_name: "mutation-app2"
    environment:
      - SUPERVISOR_ADDRESS=mutation-orchestrator
      - SUPERVISOR_PORT=5208
      - QUEUE_ADDRESS=rabbitmq
      - QUEUE_LOGIN=myuser
      - QUEUE_PASSWORD=mypassword
      - QUEUE_PORT=5672
      - OPTL_COLLECTOR=http://collector:4317
    networks:
      - main-bridge
      - oltp-bridge
    links: 
      - mutation-orchestrator
      - rabbitmq
        
  mutation-app3:
    image: mutation-app:latest
    container_name: "mutation-app3"
    environment:
      - SUPERVISOR_ADDRESS=mutation-orchestrator
      - SUPERVISOR_PORT=5208
      - QUEUE_ADDRESS=rabbitmq
      - QUEUE_LOGIN=myuser
      - QUEUE_PASSWORD=mypassword
      - QUEUE_PORT=5672
      - OPTL_COLLECTOR=http://collector:4317
    networks:
      - main-bridge
      - oltp-bridge
    links:
      - mutation-orchestrator
      - rabbitmq
  
  mutation-orchestrator:
    image: mutation-seeker-orchestrator:latest
    container_name: "mutation-orchestrator"
    environment:
      - QUEUE_ADDRESS=rabbitmq
      - QUEUE_LOGIN=myuser
      - QUEUE_PASSWORD=mypassword
      - QUEUE_PORT=5672
      - ASPNETCORE_URLS=http://0.0.0.0:5208
      - MONGO_CONNECTION_STRING=mongodb://root:example@mongo:27017
      - DATABASE_NAME=mutation
      - COLLECTION_NAME=mutation
      - OPTL_COLLECTOR=http://collector:4317
    networks:
      - main-bridge
      - mongo-bridge
      - oltp-bridge
    links: 
      - mongo
      - rabbitmq

  mongo:
    container_name: "mongo"
    image: mongo
    ports:
        - "27017:27017"
    volumes:
      - ./mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - mongo-bridge